FROM python:3.6

RUN mkdir /app
COPY ./flask-saml2/ /app/flask-saml2/
WORKDIR /app
RUN ls /app/flask-saml2
RUN pip3 install -e /app/flask-saml2/.
RUN pip3 install -r /app/flask-saml2/tests/requirements.txt
RUN cat flask-saml2/examples/sp2.bas | sed "s/WWWXXXYYYZZZ/AAABBBCCCDDD/g" > flask-saml2/examples/sp2.py
RUN chmod +x flask-saml2/examples/sp2.py

EXPOSE 9000

CMD ["flask-saml2/examples/sp2.py"]
